name: CD

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: monaco_rgpd
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: monaco_rgpd_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://monaco_rgpd:postgres@localhost:5432/monaco_rgpd_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install JavaScript dependencies
        run: npm ci

      - name: Build Vite assets
        run: npm run build

      - name: Set up database
        run: |
          bin/rails db:create
          bin/rails db:schema:load

      - name: Run tests
        run: bin/rails test

      - name: Run system tests
        run: bin/rails test:system

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 188.245.95.182 >> ~/.ssh/known_hosts
          ssh-keyscan -H 168.119.155.205 >> ~/.ssh/known_hosts

      - name: Create Kamal secrets
        run: |
          mkdir -p .kamal
          cat > .kamal/secrets << EOF
          KAMAL_REGISTRY_PASSWORD=${{ secrets.DOCKER_PASSWORD }}
          RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}
          APP_HOST=${{ secrets.APP_HOST }}
          MAILER_FROM_EMAIL=${{ secrets.MAILER_FROM_EMAIL }}
          EOF

      - name: Deploy with Kamal
        run: |
          gem install kamal
          kamal deploy

      - name: Cleanup
        if: always()
        run: rm -f .kamal/secrets
